#!/bin/bash

PROJECTROOT=`pwd`

# Copy all files staged for commit to temporary directory
# http://stackoverflow.com/a/3068990/1549881
TEMPDIR=$GIT_DIR/TEMP
rm $TEMPDIR -fr
mkdir $TEMPDIR -p
cd $PROJECTROOT
git checkout-index --prefix=$TEMPDIR/ -af

# Move to temporary directory and check files with php interpreter
cd $TEMPDIR

RES=$((find . -name \*.php -print0 | xargs -I % -0 sh -c 'php -l % >/dev/null || :' )2>&1)
if [ "$RES" != "" ]; then
    echo ""
    echo "PHP syntax error(s), canceling your commit."
    echo ""
    echo "$RES"
    echo ""
    echo "Fix your syntax and add changes to your commit"
    echo ""
    exit 1
fi

# moving back to original directory
cd $PROJECTROOT
